POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVOYW1lMSIsImlkIjoiNWRiOGE5YmE3YTUxNTI0OGMyMWI5NGM5IiwiaWF0IjoxNTcyNDcyODIzfQ.bsIHPhwJwlQU2odJe4F5EhQ0GARB9auRSztU-aiOzs4

{
  "title": "Blog-F",
  "author": "F-etu F-suku",
  "url": "https://fff-blog.com",
  "likes": 30
}
